description: Fine-tune on ProphetNet

target:
  service: aml
  name: australiav100cl

#target:
#  service: amlk8s
##  name: itpeastusv100cl
##  name: itpeusp100cl
##  name: itpscusv100cl
#  name: itpeusp100cl
#  vc: resrchvc

#target:
#  service: amlk8s
#  name: itpeastusv100cl
#  vc: resrchvc

#target:
#  service: amlk8s
##  name: itplabrr1cl1
#  name: itpeastusv100cl
#  vc: resrchvc

# pt target list amlk8s
# pt target list aml


environment:
  image: yaobl001/torch_with_apex:1.3
#  image: yaobl001/pycocoevalcap:1.3_azc
  setup:
    - export PYTHONIOENCODING=utf-8
    - pip install --user tensorboard tensorboardX pycocoevalcap nltk argparse numpy
code:
  local_dir: $CONFIG_DIR/src

jobs:
- name: dailydialog
  sku: G4
  command:
#  - sh finetune/dailydialog/job.sh
  - sh jobs/dailydialog/seq2seq_finetune.sh
#- name: personachat
#  sku: G4
#  command:
#  - sh finetune/personachat/job.sh
#- name: dstc7avsd
#  sku: G4
#  command:
#  - sh finetune/dstc7avsd/job.sh

storage:
  my_input:
    storage_account_name: wchen2
    container_name: dialogue
    mount_dir: /mnt/dialogue

